apiVersion: v1
kind: ServiceAccount
metadata:
  name: alb-ingress-controller-sa  # Name of your ALB Ingress Controller service account
  namespace: kube-system            # Namespace where the ALB Ingress Controller is deployed
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::381492167245:role/eks-alb-role
