apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: tf-eks
  region: us-east-1
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cliente1-access
      namespace: cliente1
      labels: {cliente: "cliente1"}
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::381492167245:policy/ec2-network-interfaces
    - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
